# Generated by Django 4.2.29 on 2026-03-04 08:55

import datetime
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("developer", "developer"),
                            ("member", "member"),
                            ("leader", "leader"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "userType",
                    models.CharField(
                        choices=[
                            ("student", "Current Student"),
                            ("alumnus", "Alumnus"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "registrationNumber",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("phone", models.CharField(default="0712345678", max_length=15)),
                ("homeCounty", models.CharField(default="county", max_length=50)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("full_name", models.CharField(default="full name", max_length=100)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
                ),
                ("yearOfStudy", models.IntegerField(blank=True, null=True)),
                ("graduationYear", models.IntegerField(blank=True, null=True)),
                (
                    "currentOccupation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("workplace", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "swappable": "AUTH_USER_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_name", models.CharField(max_length=100)),
                ("class_image", models.ImageField(upload_to="ministries")),
                ("class_description", models.TextField()),
                ("class_chair", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("reply", models.TextField(blank=True, null=True)),
                ("replied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Devotional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="devotionals/"),
                ),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name="Eteam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_name", models.CharField(max_length=100)),
                ("team_image", models.ImageField(upload_to="ministries")),
                ("team_description", models.TextField()),
                ("team_chair", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_image", models.ImageField(upload_to="events")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("event_description", models.TextField()),
                ("event_venue", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spiritual_year", models.CharField(max_length=50)),
                (
                    "current_spiritual_year",
                    models.CharField(default="2024/2025", max_length=50),
                ),
                (
                    "group_image",
                    models.ImageField(blank=True, null=True, upload_to="execs"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery")),
                (
                    "image_category",
                    models.CharField(
                        choices=[
                            ("event", "event"),
                            ("service", "service"),
                            ("fellowship", "fellowship"),
                            ("outdoors", "outdoors"),
                        ],
                        max_length=50,
                    ),
                ),
                ("image_to_show_on_website", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ministry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ministry_name", models.CharField(max_length=100)),
                ("ministry_image", models.ImageField(upload_to="ministries")),
                ("ministry_description", models.TextField()),
                ("ministry_chair", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "ministries",
            },
        ),
        migrations.CreateModel(
            name="Testimony",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testimony_giver", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="testimonies")),
                ("position", models.CharField(max_length=100)),
                ("testimony", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Testimonies",
            },
        ),
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reset_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leader_name", models.CharField(max_length=150)),
                ("leader_image", models.ImageField(upload_to="leaders")),
                (
                    "leader_position",
                    models.CharField(
                        choices=[
                            ("Chairperson", "Chairperson"),
                            ("Vice Chairperson", "Vice Chairperson"),
                            ("Secretary", "Secretary"),
                            ("Treasurer", "Treasurer"),
                            ("Vice Secretary", "Vice Secretary"),
                            ("Organizing Secretary", "Organizing Secretary"),
                            ("Librarian", "Librarian"),
                            ("Missions Coordinator", "Missions Coordinator"),
                            ("Technical Coordinator", "Technical Coordinator"),
                            ("Music Director", "Music Director"),
                            ("Prayer Secretary", "Prayer Secretary"),
                            ("STEM Staff", "STEM Staff"),
                        ],
                        max_length=150,
                    ),
                ),
                ("leader_description", models.TextField()),
                ("leader_contact", models.CharField(max_length=50)),
                (
                    "exec_year",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.exec",
                    ),
                ),
            ],
        ),
    ]
