# Generated by Django 4.2.29 on 2026-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_update_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_image",
            field=models.ImageField(blank=True, null=True, upload_to="events"),
        ),
    ]
