# Generated by Django 4.2.29 on 2026-03-20 16:59

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_event_event_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Devotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("written_by", models.CharField(max_length=100)),
                ("scripture_reference", models.CharField(max_length=100)),
                ("content", django_ckeditor_5.fields.CKEditor5Field()),
                ("image", models.ImageField(upload_to="devotions/")),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
        ),
    ]
