# Generated by Django 4.2.29 on 2026-03-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_devotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="exec",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
