# Generated by Django 4.2.29 on 2026-03-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_exec_is_current"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialCommittee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("committee_name", models.CharField(max_length=100)),
                ("committee_image", models.ImageField(upload_to="ministries")),
                ("committee_description", models.TextField()),
                ("committee_chair", models.CharField(max_length=50)),
                ("committee_chair_number", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Special Committee",
                "verbose_name_plural": "Special Committees",
            },
        ),
    ]
