# Generated by Django 4.2.29 on 2026-03-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_specialcommittee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class",
            old_name="class_chair",
            new_name="class_chair_name",
        ),
        migrations.RenameField(
            model_name="eteam",
            old_name="team_chair",
            new_name="team_chair_name",
        ),
        migrations.RenameField(
            model_name="ministry",
            old_name="ministry_chair",
            new_name="ministry_chair_name",
        ),
        migrations.AddField(
            model_name="class",
            name="class_chair_number",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="ministry",
            name="ministry_chair_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
