# Generated by Django 4.2.29 on 2026-04-01 20:59

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_rename_class_chair_class_class_chair_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SemesterTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.CharField(max_length=250)),
                ("verse_reference", models.CharField(max_length=100)),
                ("verse_text", models.CharField(max_length=200)),
                ("spiritual_year", models.CharField(max_length=50)),
                ("semester_number", models.CharField(max_length=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="class",
            name="class_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="eteam",
            name="team_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="leader",
            name="leader_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="ministry",
            name="ministry_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name="specialcommittee",
            name="committee_description",
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
