# Generated by Django 4.2.29 on 2026-04-02 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_semestertheme_alter_class_class_description_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Devotional",
        ),
        migrations.AlterField(
            model_name="semestertheme",
            name="description",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="semestertheme",
            name="verse_text",
            field=models.TextField(max_length=250),
        ),
    ]
