# Generated by Django 6.0.3 on 2026-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_devotional_alter_semestertheme_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='eteam',
            name='team_description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='leader',
            name='leader_description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ministry',
            name='ministry_description',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='specialcommittee',
            name='committee_description',
            field=models.TextField(max_length=600),
        ),
    ]
