# Generated by Django 4.2.29 on 2026-04-25 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0011_alter_class_class_description_alter_customuser_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testimony",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimony",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testimony",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="testimony",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_testimonies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonies"),
        ),
        migrations.AlterField(
            model_name="testimony",
            name="position",
            field=models.CharField(blank=True, default="Member", max_length=100),
        ),
    ]
