# Generated by Django 4.2.29 on 2026-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_testimony_is_approved_testimony_reviewed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimony",
            name="image",
            field=models.ImageField(null=True, upload_to="testimonies"),
        ),
    ]
