# Generated by Django 4.2.29 on 2026-08-14 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_customuser_new_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleStudySemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('registration_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bible Study Semester',
                'verbose_name_plural': 'Bible Study Semesters',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BibleStudyEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('waitlisted', 'Waitlisted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('assigned_group', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='website.biblestudysemester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_study_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bible Study Enrollment',
                'verbose_name_plural': 'Bible Study Enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('user', 'semester')},
            },
        ),
    ]
